<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>PyhopperGhDemo</AssemblyName>
    <RootNamespace>PyhopperGhDemo</RootNamespace>
    <TargetExt>.gha</TargetExt>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RhinoSystemDir Condition="'$(RhinoSystemDir)' == ''">C:\Program Files\Rhino 8\System</RhinoSystemDir>
    <GrasshopperDir Condition="'$(GrasshopperDir)' == ''">C:\Program Files\Rhino 8\Plug-ins\Grasshopper</GrasshopperDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />

    <Reference Include="RhinoCommon">
      <HintPath>$(RhinoSystemDir)\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Grasshopper">
      <HintPath>$(GrasshopperDir)\Grasshopper.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>$(GrasshopperDir)\GH_IO.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Eto">
      <HintPath>$(RhinoSystemDir)\Eto.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
